//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_EX_HOCSINH.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EF_EX_HOCSINH.Helper.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChuaTonTai.
        /// </summary>
        internal static string ChuaTonTai {
            get {
                return ResourceManager.GetString("ChuaTonTai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong Hop le NgSinh.
        /// </summary>
        internal static string KhongHopleNgSinh {
            get {
                return ResourceManager.GetString("KhongHopleNgSinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LopMax.
        /// </summary>
        internal static string LopMax {
            get {
                return ResourceManager.GetString("LopMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que Quan KHL.
        /// </summary>
        internal static string QueQuanKHL {
            get {
                return ResourceManager.GetString("QueQuanKHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So KT Qua dai.
        /// </summary>
        internal static string SoKTQuadai {
            get {
                return ResourceManager.GetString("SoKTQuadai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So KT Qua Ngan.
        /// </summary>
        internal static string SoKTQuaNgan {
            get {
                return ResourceManager.GetString("SoKTQuaNgan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So Tu Ngan.
        /// </summary>
        internal static string SoTuNgan {
            get {
                return ResourceManager.GetString("SoTuNgan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThanhCong.
        /// </summary>
        internal static string ThanhCong {
            get {
                return ResourceManager.GetString("ThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThatBai.
        /// </summary>
        internal static string ThatBai {
            get {
                return ResourceManager.GetString("ThatBai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrungMa.
        /// </summary>
        internal static string TrungMa {
            get {
                return ResourceManager.GetString("TrungMa", resourceCulture);
            }
        }
    }
}
